import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { NotificationProvider } from "@/contexts/NotificationContext";
import { Header } from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthProvider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("rerendered layout");

  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <NotificationProvider>
            <Header />
            <div className="h-full pt-[80px]">{children}</div>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
