import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { NotificationProvider } from "@/contexts/NotificationContext";
import { Header } from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <NotificationProvider>
          <div className="h-full pt-[80px]">{children}</div>
        </NotificationProvider>
      </body>
    </html>
  );
}
